/**
 * <%= controller %>
 *
 * <%= controller %> Controller generated by Helpper framework
 *
 */
import * as express from 'express';
import { BaseController } from '../core/BaseController';

export class <%= controller %>Controller extends BaseController {

    /**
     * Index
     * 
     * Index method
     * 
     * @public
     * @author Generated
     * @param  {express.Request}  req the express request object
     * @param  {express.Response} res the express response object
     * @return {void}
     */
    public index(req: express.Request, res: express.Response): void {
        this.showSucess( 'Olá mundo', res );
    }
}
