 /**
 * <%= model %>
 *
 * Generated by Helpper framework
 *
 * @author Gustavo Vilas Bôas
 * @since  01-2017
 */
import {BaseModel}    from '../core/BaseModel';
import * as Sequelize from 'sequelize';

export class <%= model %> extends BaseModel {

    /**
     * _is_sql
     * 
     * @type {boolean} _is_sql indicates if the current model is sql or not
     * @protected
     */
    protected _is_sql: boolean = true;

    /**
     * _name
     * 
     * @type {string} _name the name of the model
     * @protected
     */
    protected _name: string = '<%= table %>';

    /**
     * _fields
     * 
     * @type {Schema} _fields a MongoDB Schema
     * @type {Object} _fields a Sequelize model object
     * @protected
     */
    protected _fields: Object = {
        <% for ( let f in fields ) { %>
        <%= fields[f]['name'] %> : {
        <% for ( let c in fields[f]['columns'] ) { -%>
        <% if ( fields[f]['columns'][c]['key'] != 'type' && typeof fields[f]['columns'][c]['value'] == 'string' ) { -%>
        <%= fields[f]['columns'][c]['key'] %>: '<%= fields[f]['columns'][c]['value'] %>', 
        <% } else { -%>
        <%= fields[f]['columns'][c]['key'] + ": "+fields[f]['columns'][c]['value']+"," %> 
        <% } -%>
        <% } -%>
        field: '<%= fields[f]['field'] %>'
        },
        <% } %>
    };
};

