/**
 * WelcomeController
 *
 * Default Controller generated by Helpper framework
 *
 * @author Gustavo Vilas Bôas
 * @since  02-2017
 */
import * as express from 'express';
import { BaseController } from '../core/BaseController';

export class WelcomeController extends BaseController {

    /**
     * Welcome
     * 
     * Welcome guys
     * 
     * @public
     * @author Gustavo Vilas Boas
     * @since  02-2017
     * @param  {express.Request}  req the express request object
     * @param  {express.Response} res the express response object
     * @return {void}
     */
    public index(req: express.Request, res: express.Response): void {
        this.showSucess( 'Olá mundo', res );
    }
}
